# Generated by Django 3.1.7 on 2021-04-02 11:36

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('closed', models.BooleanField(default=False)),
                ('impact', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=50)),
                ('header', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.CharField(choices=[('TEAMS', 'Microsoft Teams'), ('EMAIL', 'Email')], max_length=50)),
                ('address', models.CharField(help_text='Enter Incoming Webhook URL or Email address depending on the notification type', max_length=400)),
                ('subject', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('INCIDENT', 'Incident'), ('MAINTENANCE', 'Maintenance')], default='Incident', max_length=20), size=None)),
                ('topic', models.ManyToManyField(blank=True, to='statusapp.Topic')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('header', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statusapp.topic')),
            ],
        ),
        migrations.CreateModel(
            name='IncidentUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('IDENTIFIED', 'Identified'), ('INVESTIGATING', 'Investigating'), ('RESOLVED', 'Resolved')], max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statusapp.incident')),
            ],
        ),
        migrations.AddField(
            model_name='incident',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statusapp.topic'),
        ),
    ]
