# Generated by Django 3.1.7 on 2021-04-02 11:44

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('statusapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlist',
            name='subject',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('INCIDENT', 'Incident'), ('MAINTENANCE', 'Maintenance')], default='Incident', max_length=20),
        ),
    ]
