# Generated by Django 3.1.7 on 2021-04-02 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statusapp', '0002_auto_20210402_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='description',
        ),
    ]
