# Generated by Django 3.1.7 on 2021-04-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statusapp', '0003_remove_maintenance_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
