# Generated by Django 3.1.7 on 2021-04-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statusapp', '0004_auto_20210402_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlist',
            name='all_topic',
            field=models.BooleanField(default=False, help_text='If selected, the above Topic dropdown has no effect', verbose_name='All topics'),
        ),
    ]
