# Generated by Django 3.1.7 on 2021-04-05 15:47

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('statusapp', '0006_auto_20210405_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.CharField(choices=[('TEAMS', 'Microsoft Teams'), ('EMAIL', 'Email')], max_length=50)),
                ('address', models.CharField(help_text='Enter Incoming Webhook URL or Email address depending on the notification type', max_length=400)),
                ('all_topic', models.BooleanField(default=False, help_text='If selected, above topics will automatically be unselected', verbose_name='All topics')),
                ('subject', multiselectfield.db.fields.MultiSelectField(choices=[('INCIDENT', 'Incident'), ('MAINTENANCE', 'Maintenance')], default='Incident', max_length=20)),
                ('topic', models.ManyToManyField(blank=True, to='statusapp.Topic')),
            ],
        ),
        migrations.DeleteModel(
            name='NotificationList',
        ),
    ]
