# Generated by Django 3.1.7 on 2021-04-06 10:12

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('statusapp', '0008_auto_20210406_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification',
            field=models.CharField(choices=[('teams', 'Microsoft Teams'), ('email', 'Email')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='subject',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('incident', 'Incident'), ('maintenance', 'Maintenance')], default='Incident', max_length=20),
        ),
    ]
