# Generated by Django 3.1.7 on 2021-04-06 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statusapp', '0010_auto_20210406_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentupdate',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_updates', to='statusapp.incident'),
        ),
    ]
